baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Dropdown'
weight = 10

[[menus.main]]
name = 'Left Sidebar'
pageRef = 'left-sidebar'
url = '/left-sidebar/'
weight = 20

[[menus.main]]
name = 'Right Sidebar'
pageRef = 'right-sidebar'
url = '/right-sidebar/'
weight = 30

[[menus.main]]
name = 'No Sidebar'
pageRef = 'no-sidebar'
url = '/no-sidebar/'
weight = 40

[[menus.main]]
name = 'Lorem ipsum dolor'
pageRef = '/a/'
weight = 10
parent='Dropdown'

[[menus.main]]
name = 'Magna phasellus'
pageRef = 'b'
url = '/b/'
weight = 20
parent='Dropdown'

[[menus.main]]
name = 'Etiam dolore nisl'
pageRef = 'c'
url = '/c/'
weight = 30
parent='Dropdown'

[[menus.main]]
name = 'Phasellus consequat'
pageRef = 'd'
url = '/d/'
weight = 40
parent='Dropdown'

[[menus.main]]
name = 'Lorem ipsum'
pageRef = 'e'
url = '/e/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Phasellus'
pageRef = 'f'
url = '/f/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Magna'
pageRef = 'g'
url = '/g/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Etium'
pageRef = 'h'
url = '/h/'
weight = 10
parent='Phasellus consequat'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
