baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Dropdown'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Left Sidebar'
pageRef = '/left-sidebar/'
weight = 20

[[menus.main]]
name = 'Right Sidebar'
pageRef = '/right-sidebar/'
weight = 30

[[menus.main]]
name = 'No Sidebar'
pageRef = '/no-sidebar/'
weight = 40

[[menus.main]]
name = 'Lorem ipsum dolor'
pageRef = '/'
weight = 10
parent='Dropdown'

[[menus.main]]
name = 'Magna phasellus'
pageRef = '/'
weight = 20
parent='Dropdown'

[[menus.main]]
name = 'Etiam dolore nisl'
pageRef = '/'
weight = 30
parent='Dropdown'

[[menus.main]]
name = 'Phasellus consequat'
pageRef = '/'
weight = 40
parent='Dropdown'

[[menus.main]]
name = 'Lorem ipsum'
pageRef = '/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Phasellus'
pageRef = '/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Magna'
pageRef = '/'
weight = 10
parent='Phasellus consequat'

[[menus.main]]
name = 'Etium'
pageRef = '/'
weight = 10
parent='Phasellus consequat'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
